import type { Metadata } from "next"
import Image from "next/image"
import Link from "next/link"
import { notFound } from "next/navigation"

import { getProject, projects } from "../../projects"

export function generateStaticParams() { return projects.map(({ slug }) => ({ slug })) }

export async function generateMetadata({ params }: { params: Promise<{ slug:string }> }): Promise<Metadata> {
  const project = getProject((await params).slug)
  return project ? { title:`${project.shortTitle} — Aymeric Dev`, description:project.summary } : {}
}

export default async function ProjectPage({ params }: { params: Promise<{ slug:string }> }) {
  const project = getProject((await params).slug)
  if (!project) notFound()
  const index = projects.findIndex(({ slug }) => slug === project.slug)
  const nextProject = projects[(index + 1) % projects.length]!
  return <>
    <header className="site-header case-header"><Link className="wordmark" href="/">Aymeric<span>Dev</span></Link><Link className="back-link" href="/#work">← All work</Link></header>
    <main className="case-main">
      <section className="case-hero shell"><div className="project-meta"><span>{project.kind}</span><span>{project.year}</span></div><h1>{project.title}</h1><p>{project.summary}</p></section>
      <div className={`case-media shell${project.slug==="r-latplan"?" image-contain":""}`}>{project.image.endsWith(".gif") ? (
        // eslint-disable-next-line @next/next/no-img-element
        <img src={project.image} alt={project.imageAlt} />
      ) : <Image src={project.image} alt={project.imageAlt} width={1920} height={1080} priority />}</div>
      <section className="case-content shell">
        <div className="case-facts"><p className="eyebrow">Scope</p><ul>{project.tags.map(tag => <li key={tag}>{tag}</li>)}</ul><a href={project.repository} target="_blank" rel="noreferrer">View repository ↗</a></div>
        <div className="case-story">
          <div><p className="eyebrow">The challenge</p><p className="case-lead">{project.challenge}</p></div>
          <div><p className="eyebrow">The approach</p><ol>{project.approach.map((item,i) => <li key={item}><span>0{i+1}</span>{item}</li>)}</ol></div>
          <div><p className="eyebrow">The outcome</p><p className="case-lead">{project.outcome}</p></div>
        </div>
      </section>
      {project.slug === "r-latplan" && <section className="comparison shell">
        <div className="section-heading"><div><p className="eyebrow">Why reliability matters</p><h2>A plan must be executable—not merely plausible.</h2></div></div>
        <div className="comparison-grid">
          <figure><Image src="/images/projects/latplan-invalid-plan.png" alt="Visually invalid plan generated by the baseline Latplan system" width={1116} height={154}/><figcaption><span>Baseline</span>Visual artifacts break the plan.</figcaption></figure>
          <figure><Image src="/images/projects/rlatplan-valid-plan.png" alt="Valid visual plan generated by R-Latplan" width={1140} height={269}/><figcaption><span>R-Latplan</span>Every transition remains visually valid and executable.</figcaption></figure>
        </div>
      </section>}
      {project.slug === "bowling-pin-detection" && <section className="case-quote shell"><div className="case-quote-rating"><span aria-label="5 out of 5">★★★★★</span><small>Verified Codeur.com review</small></div><blockquote>“Aymeric demonstrated a deep understanding of the technical requirements from the outset, identifying and configuring the necessary hardware with remarkable speed and efficiency. His technical expertise is undeniable, but his ability to integrate these technical aspects into a complete solution is what truly sets him apart.”</blockquote><div className="case-quote-credit"><a className="testimonial-logo" href="https://2ds.ch/" target="_blank" rel="noreferrer"><Image src="/images/clients/2ds.svg" alt="2DS" width={144} height={65}/></a><strong>Justin Theytaz</strong><a href="https://2ds.ch/" target="_blank" rel="noreferrer">2DS, Switzerland ↗</a><span>Client · November 2023</span></div></section>}
      <Link className="next-project" href={`/work/${nextProject.slug}`}><span>Next case study</span><strong>{nextProject.shortTitle} <b>↗</b></strong></Link>
    </main>
  </>
}
