import Image from "next/image"
import Link from "next/link"

import type {Language} from "./home-content"

const content={
  fr:{
    back:"Retour à l’accueil",switchLabel:"English",switchHref:"/en/background",eyebrow:"Expérience & formation",title:"Parcours",intro:"Un parcours construit entre développement logiciel, missions clients et recherche en intelligence artificielle.",bridgeTitle:"Un même fil conducteur",bridge:"Avant de me spécialiser en intelligence artificielle, j’ai conçu pendant plusieurs années des produits web et des outils métier en production. Cette expérience nourrit aujourd’hui une approche de l’IA attentive à la qualité des données, à l’expérimentation et au déploiement.",achievements:"Réalisations",related:"Projet associé",projectsTitle:"Explorer mon travail",aiProjects:"Projets en intelligence artificielle",webProjects:"Projets de développement web",
    entries:[
      {role:"Chercheur postdoctoral",organization:"Tampere University",period:"Oct. 2025 — mars 2026",location:"Tampere, Finlande",logo:"/images/experience/tampere-university.png",logoAlt:"Logo de Tampere University",tone:"tampere",summary:"Recherche appliquée à la modélisation de carnets d’ordres et à la prévision de séries temporelles financières.",achievements:["Développement d’un pipeline de traitement de données haute fréquence provenant de carnets d’ordres Deutsche Börse A7.","Extension et évaluation de MaRS, une architecture générative de deep learning dédiée à la modélisation des carnets d’ordres."],tags:["Deep learning","Séries temporelles","Data engineering","Finance"],project:{label:"Dynamiques d’impact de marché",href:"/work/market-impact-dynamics"}},
      {role:"Doctorat en intelligence artificielle",organization:"Sapienza Università di Roma",period:"Oct. 2021 — sept. 2025",location:"Province de Brescia, Italie",logo:"/images/experience/sapienza.png",logoAlt:"Logo de Sapienza Università di Roma",tone:"sapienza",summary:"Thèse : Learning Symbolic Planning Models from Images — apprentissage neuro-symbolique de modèles de planification interprétables directement à partir d’images.",achievements:["Conception de méthodes reliant perception visuelle, représentations symboliques et planification automatisée.","Développement et évaluation de prototypes de recherche, avec publication des résultats et mise à disposition du code."],tags:["IA neuro-symbolique","Computer vision","Planification","Recherche"],project:{label:"Voir les travaux de recherche",href:"/fr/projects/ai"}},
      {role:"Développeur logiciel freelance",organization:"Indépendant",period:"Nov. 2017 — août 2023",location:"France · À distance",mark:"AD",tone:"freelance",summary:"Conception de solutions sur mesure pour des entreprises : e-commerce, intégrations, automatisation et traitement de données.",achievements:["Développement de modules métier et d’intégrations avec des services tiers.","Création de scripts de traitement de données et de fonctionnalités backend en Python et PHP."],tags:["Python","PHP","APIs","E-commerce"],project:{label:"Voir les projets web",href:"/fr/projects/web"}},
      {role:"Développeur web full-stack",organization:"Ozon Digital",period:"Juin 2019 — mars 2020",location:"Courbevoie, France",mark:"OZON",tone:"ozon",summary:"Développement en agence de sites e-commerce, de thèmes et de fonctionnalités métier jusqu’à leur mise en production.",achievements:["Développement avec Laravel et Symfony.","Création et évolution de thèmes et modules PrestaShop dans un contexte agile."],tags:["Laravel","Symfony","PrestaShop","Agile"],project:{label:"Découvrir Espace Foot",href:"/fr/projects/web"}},
    ]
  },
  en:{
    back:"Back to home",switchLabel:"Français",switchHref:"/fr/parcours",eyebrow:"Experience & education",title:"Background",intro:"A path shaped by software engineering, client delivery and artificial intelligence research.",bridgeTitle:"One continuous thread",bridge:"Before specialising in artificial intelligence, I spent several years building production web products and business tools. That experience now informs an AI practice grounded in data quality, experimentation and deployment.",achievements:"Selected work",related:"Related project",projectsTitle:"Explore my work",aiProjects:"Artificial intelligence projects",webProjects:"Web development projects",
    entries:[
      {role:"Postdoctoral researcher",organization:"Tampere University",period:"Oct. 2025 — Mar. 2026",location:"Tampere, Finland",logo:"/images/experience/tampere-university.png",logoAlt:"Tampere University logo",tone:"tampere",summary:"Applied research into limit-order-book modelling and financial time-series forecasting.",achievements:["Developed a high-frequency data-processing pipeline for Deutsche Börse A7 limit-order-book data.","Extended and evaluated MaRS, a generative deep-learning architecture for limit-order-book modelling."],tags:["Deep learning","Time series","Data engineering","Finance"],project:{label:"Market-impact dynamics",href:"/work/market-impact-dynamics"}},
      {role:"PhD in artificial intelligence",organization:"Sapienza University of Rome",period:"Oct. 2021 — Sept. 2025",location:"Province of Brescia, Italy",logo:"/images/experience/sapienza.png",logoAlt:"Sapienza University of Rome logo",tone:"sapienza",summary:"Thesis: Learning Symbolic Planning Models from Images — neuro-symbolic AI for learning interpretable planning models directly from images.",achievements:["Designed methods connecting visual perception, symbolic representations and automated planning.","Built and evaluated research prototypes, publishing results and releasing the accompanying code."],tags:["Neuro-symbolic AI","Computer vision","Planning","Research"],project:{label:"View research projects",href:"/en/projects/ai"}},
      {role:"Freelance software developer",organization:"Independent",period:"Nov. 2017 — Aug. 2023",location:"France · Remote",mark:"AD",tone:"freelance",summary:"Designed custom solutions for businesses across e-commerce, integrations, automation and data processing.",achievements:["Developed business modules and integrations with third-party services.","Created data-processing scripts and backend functionality in Python and PHP."],tags:["Python","PHP","APIs","E-commerce"],project:{label:"View web projects",href:"/en/projects/web"}},
      {role:"Full-stack web developer",organization:"Ozon Digital",period:"June 2019 — Mar. 2020",location:"Courbevoie, France",mark:"OZON",tone:"ozon",summary:"Agency development of e-commerce websites, themes and business functionality through to production.",achievements:["Developed applications with Laravel and Symfony.","Built and evolved PrestaShop themes and modules within an agile team."],tags:["Laravel","Symfony","PrestaShop","Agile"],project:{label:"Discover Espace Foot",href:"/en/projects/web"}},
    ]
  }
} as const

export function ExperienceContent({language}:{language:Language}){
  const t=content[language]
  return <>
    <header className="site-header case-header"><Link className="wordmark" href={`/${language}`}>Aymeric<span>Dev</span></Link><Link className="back-link" href={`/${language}`}>← {t.back}</Link><Link className="language-switch" href={t.switchHref}>{t.switchLabel} ↗</Link></header>
    <main className="experience-page shell">
      <section className="experience-hero"><p className="eyebrow">{t.eyebrow}</p><h1>{t.title}</h1><p>{t.intro}</p></section>
      <section className="career-bridge"><span>01</span><div><h2>{t.bridgeTitle}</h2><p>{t.bridge}</p></div></section>
      <section className="experience-timeline">{t.entries.map((entry,index)=><article className="experience-entry" key={`${entry.organization}-${entry.period}`}>
        <div className="timeline-index"><span>{String(index+1).padStart(2,"0")}</span></div>
        <div className={`experience-logo ${entry.tone}`}>{"logo" in entry?<Image src={entry.logo} alt={entry.logoAlt} fill sizes="96px"/>:<strong>{entry.mark}</strong>}</div>
        <div className="experience-copy"><div className="experience-meta"><span>{entry.period}</span><span>{entry.location}</span></div><h2>{entry.role}</h2><h3>{entry.organization}</h3><p className="experience-summary">{entry.summary}</p><p className="experience-label">{t.achievements}</p><ul className="experience-achievements">{entry.achievements.map(item=><li key={item}>{item}</li>)}</ul><ul className="tag-list">{entry.tags.map(tag=><li key={tag}>{tag}</li>)}</ul><Link className="experience-project-link" href={entry.project.href}>{entry.project.label} ↗</Link></div>
      </article>)}</section>
      <section className="experience-next"><p className="eyebrow">{t.projectsTitle}</p><div><Link href={`/${language}/projects/ai`}>{t.aiProjects}<span>↗</span></Link><Link href={`/${language}/projects/web`}>{t.webProjects}<span>↗</span></Link></div></section>
    </main>
  </>
}
